name: Python Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'  # 指定你想要使用的Python版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python -i https://pypi.tuna.tsinghua.edu.cn/simple  
          pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pillow    (使用PIL模块)
          pip install opencv-contrib-python -i https://pypi.tuna.tsinghua.edu.cn/simple      （必须安装否则无法使用.face）
          pip install -i https://pypi.tuna.tsinghua.edu.cn/simple numpy
      - name: Run Python script
        run: 录入人脸信息.py  # 根据你的项目修改脚本名称

